name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: gh-metrics/metrics@master
        with:
            token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
            user: tobifroe
            template: classic
            base: header, activity, community, repositories #, metadata
            config_animations: yes
            config_timezone: Europe/Berlin
            optimize: no
            use_prebuilt_image: yes  
            plugin_achievements: yes
            plugin_achievements_display: compact
            plugin_achievements_threshold: B
            plugin_achievements_secrets: yes
            plugin_isocalendar: yes
            plugin_isocalendar_duration: full-year
            plugin_languages: yes
            plugin_languages_details: percentage
            plugin_lines: yes
            plugin_repositories: yes
            plugin_repositories_featured: tobifroe/klog, tobifroe/nixos-config
            plugin_traffic: yes
            plugin_activity: yes
            plugin_stars: yes
            plugin_stars_limit: 3
